#!/bin/bash
#####################################
#website  access test
#Copyright (c) 2016 <zhongx@knownsec.com>
#Copyright (c) 2016   KNOWNSEC INC
#Author: Xavier
#Version: 2016/11/29 13:15 v0.1.0
#####################################

Type="http"
num="1"

usage(){
  echo  "Usage:"
  echo  "  chkuri [参数] ..."
  echo  "eg: chkuri -d www.yunaq.com -g 11 -n 2"
  echo  "参数选择:"
  echo  "-d     需要测试的域名"
  echo  "-t     网站请求协议类型(http/https)默认使用http"
  echo  "-g     域名所在分组id"
  echo  "-n     测试次数(默认测试一次)"
  echo  "-s     测试源站访问情况（源站ip）"
  echo  "-h     查看脚本使用帮助"
}

while getopts ":d:t:g:n:s:h" arg
do
  case $arg in
    d)
      host="$OPTARG";;
    t)
      Type="$OPTARG";;
    g)
      group_id="$OPTARG";;
    n)
      num="$OPTARG";;
    s)
      source_ip="$OPTARG";;
    h)
      usage
      exit 0;;
    ?)
      usage
      exit 0;;
  esac
done

chk_uri(){
  for((j=1;j<=$num;j++))
  do
    if [[ $group_id == "" ]];then
      echo "分组id不能为空"
      exit
    fi
    echo "第" $j "次测试"
    for i in `getnode -g $group_id --wan`
      do
        status=`curl -I -m 10 -o /dev/null -s -w %{http_code}"\n"  -H "host:$host" $Type://$i/ -k`
          if [ $status  -eq 200 ];then
               echo "$host>>$i is ok"
            else
              echo "$host>>$i get error $status"
          fi
    done
  done
}
chk_uri_s(){
  if [[ $source_ip == "" ]];then
      echo "源站ip不能为空"
      exit
  fi
  status=`curl -I -m 10 -o /dev/null -s -w %{http_code}"\n"  -H "host:$host" $Type://$source_ip/ -k`
  if [ $status  -eq 200 ];then
    echo "$host>>$i is ok"
  else
    echo "$host>>$i get error $status"
  fi
}

if [[ $OPTIND == 1 ]];then
  usage
  exit
else
  if [[ $source_ip == "" ]];then
    chk_uri
  else
    chk_uri_s
  fi
fi
