#!/bin/bash

function usage()
{
cat <<EOF
get_idc_domain chongqing
get_idc_domain chongqing-cuc
EOF
}

function get_wip()
{
	mkdir -p ~/tmp/$1 && for i in `getnode -a | grep $1 | awk '{print $2}'` ; do getnode -v $i | awk '{print $2}' ; done > ~/tmp/$1/tmp1.list
	for i in `cat ~/tmp/$1/tmp1.list`;do getnode -l $i;done  > ~/tmp/$1/tmp2.list
	echo [$1] && cat ~/tmp/$1/tmp2.list |awk '{print $3}'
}

if [[ $1 == '-h' || $1 == '--help' ]];then
	usage
	exit 0
fi

function get_all_wip()
{
	for idc_name in `getnode -a | awk '{print $1}' | awk -F "-" '{print $(NF-1)"-"$NF}' | tr -d "[0-9]" |sort | uniq` ;do get_wip $idc_name;done
}

get_all_wip
